name: Deploy Index-TTS to Modal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Modal
        run: pip install modal
      
      - name: Configure Modal
        run: |
          # Create the .modal directory
          mkdir -p ~/.modal
          
          # Create the token file with proper permissions
          touch ~/.modal.toml
          chmod 600 ~/.modal.toml
          
          # Write the token configuration - SIMPLIFIED FORMAT
          cat > ~/.modal.toml << EOF
          [user]
          token_id = "${{ secrets.MODAL_TOKEN_ID }}"
          token_secret = "${{ secrets.MODAL_TOKEN_SECRET }}"
          EOF
      
      - name: Deploy to Modal
        run: |
          # Deploy directly without verification
          modal deploy modal_app.py
      
      - name: Verify deployment
        run: |
          echo "Deployment completed. The service is now available at:"
          echo "https://${{ secrets.MODAL_USERNAME }}--index-tts-inference-inference-api.modal.run"
