name: Deploy Index-TTS to Modal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal-client
          pip install torch torchaudio numpy
          pip install fastapi

      - name: Configure Modal
        run: |
          mkdir -p ~/.modal
          touch ~/.modal.toml
          chmod 600 ~/.modal.toml
          cat > ~/.modal.toml << EOF
          [${{ secrets.MODAL_USERNAME }}]
          token_id = "${{ secrets.MODAL_TOKEN_ID }}"
          token_secret = "${{ secrets.MODAL_TOKEN_SECRET }}"
          active = true
          EOF

      - name: Deploy to Modal
        run: |
          modal deploy modal_app.py

      - name: Verify deployment
        run: |
          echo "Deployment completed. The service is now available at:"
          echo "https://${{ secrets.MODAL_USERNAME }}--index-tts-inference-fastapi-app.modal.run"
